version: '2'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wsr
    ports:
      - "3307:3306"
    volumes:
      - "./DDL.sql:/docker-entrypoint-initdb.d/1.sql"

  lab18:
    image: dubaleco/laba18
    container_name: laba18
    depends_on:
      - db
    ports:
      - "8080:8080"
